//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aliyun.OSS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aliyun.OSS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EndOperation has been called on this asyncResult..
        /// </summary>
        internal static string ExceptionEndOperationHasBeenCalled {
            get {
                return ResourceManager.GetString("ExceptionEndOperationHasBeenCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter is empty or null..
        /// </summary>
        internal static string ExceptionIfArgumentStringIsNullOrEmpty {
            get {
                return ResourceManager.GetString("ExceptionIfArgumentStringIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response is invalid or unable to parse..
        /// </summary>
        internal static string ExceptionInvalidResponse {
            get {
                return ResourceManager.GetString("ExceptionInvalidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error is returned from Server..
        /// </summary>
        internal static string ExceptionUnknownError {
            get {
                return ResourceManager.GetString("ExceptionUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xlsx    application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
        ///xltx    application/vnd.openxmlformats-officedocument.spreadsheetml.template
        ///potx    application/vnd.openxmlformats-officedocument.presentationml.template
        ///ppsx    application/vnd.openxmlformats-officedocument.presentationml.slideshow
        ///pptx    application/vnd.openxmlformats-officedocument.presentationml.presentation
        ///sldx    application/vnd.openxmlformats-officedocument.presentationml.slide
        ///docx    application/vnd.openxmlformats-of [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MimeData {
            get {
                return ResourceManager.GetString("MimeData", resourceCulture);
            }
        }
    }
}
